<!DOCTYPE html><html lang="zh-CN"><head><title>Go Errors Handling</title><meta http-equiv="content-type" content="text/html; charset=utf-8"><meta name="viewport" content="width=device-width, initial-scale=0.5"><link rel="icon" type="image/svg+xml" href="/favicon.svg"><link rel="stylesheet" href="/css/highlight/xcode.min.css"><link rel="stylesheet" href="/css/bootstrap/bootstrap-tooltips.css"><link rel="stylesheet" href="/css/post.css"><script src="/js/jquery.min.js"></script><meta name="generator" content="Hexo 5.2.0"></head><body><script>if (/mobile/i.test(navigator.userAgent) || /android/i.test(navigator.userAgent)) {
  document.body.classList.add('mobile')
}</script><div><div class="inner"><h2>Go Errors Handling</h2><p>如何正确而优雅地处理错误是每个 Go 程序员都要思考的一个问题。Go 处理错误的方式不同于主流语言，比如 Java 使用 <code>try ... catch ... finally</code> 语句去处理程序的异常/错误，Go 中没有这样的错误处理语句。</p>
<p>Go 的错误处理也是其它编程语言的用户使用 Go 语言时经常谈到的话题，大多数人都认为 Go 的错误处理方式会导致代码里有太多繁琐的、重复的 <code>if err ≠ nil &#123;&#125;</code>。但目前 Go 官方并没有改进错误处理机制的计划，因此我们也只能继续使用目前的方式去处理错误。</p>
<h2 id="错误处理策略"><a href="#错误处理策略" class="headerlink" title="错误处理策略"></a>错误处理策略</h2><p>在 Go 中，错误处理意味着检查错误值并做出决定，Go 错误处理机制是基于其以下语言特性：</p>
<ol>
<li>Errors are values，即在 Go 中错误就是值，就像 <code>&quot;hello world&quot;</code> 之于 <code>string</code>，我们使用变量去承载错误。Go 用户必须检查函数返回的错误的值，结合 <code>if ... else ...</code> 或者 <code>switch &#123; ... &#125;</code> 去做流程控制（终止程序执行流程、继续执行流程）；</li>
<li>函数可以有多个返回值，如果函数要返回错误，那么我们需要把错误放在多个返回值中的最后一个，形如这个函数签名：<code>func func1() (int, int, error)</code>。</li>
</ol>
<p>目前 Go 生态中，常见的错误处理策略有三种：</p>
<ol>
<li>哨兵错误（Sentinel errors）</li>
<li>错误类型（ Error types）</li>
<li>不透明错误（ Opaque errors）</li>
</ol>
<h3 id="哨兵错误"><a href="#哨兵错误" class="headerlink" title="哨兵错误"></a>哨兵错误</h3><p>预定义的、等于固定值的错误，称为哨兵错误。常见的一个哨兵错误 <code>sql.ErrNoRows</code> 是：</p>
<pre><code class="go">// ErrNoRows is returned by Scan when QueryRow doesn&#39;t return a
// row. In such a case, QueryRow returns a placeholder *Row value that
// defers this error until a Scan.
var ErrNoRows = errors.New(&quot;sql: no rows in result set&quot;)</code></pre>
<p>gorm 也有一个类似的东西：</p>
<pre><code class="go">// ErrRecordNotFound record not found error
var ErrRecordNotFound = errors.New(&quot;record not found&quot;)</code></pre>
<p><code>sql.ErrNoRows</code> 和 <code>gorm.ErrRecordNotFound</code> 的功能都是一样的，表示<strong>满足 where 子句条件的数据库记录不存在</strong>。</p>
<p>哨兵错误的处理方式是，当我们有一个 <code>err</code> 时，拿它跟目标哨兵错误做<strong>等值比较</strong>。比如：</p>
<pre><code class="go">file, err := h.Repositories.File.SelectOne(ctx, fileID)
if err != nil &#123;
  if err == sql.ErrNoRows &#123;
    return FileNotFound(ctx)
  &#125;
  return InternalServerError(ctx, err)
&#125;</code></pre>
<p>在这段代码里，当 <code>err == sql.ErrNoRows</code> 成立时，我们给客户端返回 <code>HTTP 404</code>，当 <code>err == sql.ErrNoRows</code> 不成立时，我们给客户端返回 <code>HTTP 500</code>（可能是数据库服务器宕机了）。</p>
<p>哨兵错误的处理很简单，但它有缺点。首先它缺少详细的错误信息，哨兵错误只包含一句简短的字符串信息。它的值是固定的，在程序启动的时候已经初始化，如果在程序运行的过程中改变哨兵错误的值，那就打破了你和 API 用户的约定，API 用户的代码可能就要出现不兼容或者 bug 了。举个例子，如果你在一个运行中的程序将 <code>sql.ErrNoRows</code> 改为 <code>nil</code>：</p>
<pre><code class="go">sql.ErrNoRows = nil</code></pre>
<p>那就出大问题了！</p>
<p>哨兵错误的另一个缺点是在两个包之间创建了源代码依赖关系，存在直接代码调用的包之间存在源代码依赖关系是正常的，但是不存在直接代码调用的包之间的源代码依赖关系被认为是不正常的。还是以这段代码为例：</p>
<pre><code class="go">import (
    &quot;context&quot;
    &quot;database/sql&quot;
  ...
)

...

file, err := h.Repositories.File.SelectOne(ctx, fileID)
if err != nil &#123;
  if err == sql.ErrNoRows &#123;
    return FileNotFound(ctx)
  &#125;
  return InternalServerError(ctx, err)
&#125;</code></pre>
<p>这是 controller 层的代码，离 repository 层中间隔了个 service 层。尽管 handler 层并没有跟数据库操作有关的代码，但为了识别 <code>sql.ErrNoRows</code> 并返回 <code>HTTP 404</code> 给客户端，我们还是得导入 <code>&quot;database/sql&quot;</code> 包。为了处理哨兵错误，两个没有多大关联的包之间产生了源代码依赖关系，想象一下，当项目中的许多包都导出哨兵错误值时，包与包之间存在耦合关系将变得错综复杂。</p>
<h3 id="错误类型"><a href="#错误类型" class="headerlink" title="错误类型"></a>错误类型</h3><p>错误类型指是实现了 <code>error</code> 接口的自定义类型，Go 标准库里一个不错的例子是 <code>os.PathError</code>，它提供了底层执行了什么操作、哪个路径出了问题。源码：</p>
<pre><code class="go">// PathError records an error and the operation and file path that caused it.
type PathError struct &#123;
    Op   string
    Path string
    Err  error
&#125;

func (e *PathError) Error() string &#123; return e.Op + &quot; &quot; + e.Path + &quot;: &quot; + e.Err.Error() &#125;

func (e *PathError) Unwrap() error &#123; return e.Err &#125;</code></pre>
<p>可以看到，<code>*PathError</code> 有一个 <code>Error() string</code> 方法，这表示它实现了 <code>src/builtin/builtin</code> 里的 <code>error</code> 接口：</p>
<pre><code class="go">// The error built-in interface type is the conventional interface for
// representing an error condition, with the nil value representing no error.
type error interface &#123;
    Error() string
&#125;</code></pre>
<p>这使得在任何需要返回一个 <code>error</code> 的地方，我们可以返回一个 <code>*PathError</code> ：</p>
<pre><code class="go">// openFileNolog is the Unix implementation of OpenFile.
// Changes here should be reflected in openFdAt, if relevant.
func openFileNolog(name string, flag int, perm FileMode) (*File, error) &#123;

  ...

    var r int
    for &#123;
        var e error
        r, e = syscall.Open(name, flag|syscall.O_CLOEXEC, syscallMode(perm))
        if e == nil &#123;
            break
        &#125;

        // We have to check EINTR here, per issues 11180 and 39237.
        if e == syscall.EINTR &#123;
            continue
        &#125;

        return nil, &amp;PathError&#123;Op: &quot;open&quot;, Path: name, Err: e&#125;
    &#125;

  ...

    return newFile(uintptr(r), name, kindOpenFile), nil
&#125;</code></pre>
<p>这是标准库 <code>os.OpenFile</code> 函数内部调用到的函数 <code>openFileNolog</code> ，它的第二个返回值是 <code>error</code> 类型，可以看到在第 20 行返回了 <code>&amp;PathError&#123;Op: &quot;open&quot;, Path: name, Err: e&#125;</code>。此处返回了错误类型 <code>*os.PathError</code>，比哨兵错误携带了更多有意义的上下文信息。</p>
<p>虽然错误类型为错误提供详细的上下文信息，但仍然存在问题：如果调用者要使用类型断言或 <code>type switch</code> ，那么我们就要将错误类型变为 exported，即导出的，举个例子：</p>
<pre><code class="go">package main

import (
    &quot;fmt&quot;
    &quot;os&quot;

    &quot;github.com/pkg/errors&quot;
)

func main() &#123;
    f, err := os.Open(&quot;env/.env&quot;)
    switch e := err.(type) &#123;
    case nil:
        // call succeeded, nothing to do
    case *os.PathError:
        fmt.Printf(&quot;op=%s, path=%s, err=%v&quot;, e.Op, e.Path, e.Error())
    default:
        // unknown error
    &#125;
    _ = f
&#125;</code></pre>
<p>当 <code>env/.env</code> 不存在时，会输出详细的错误信息：</p>
<pre><code class="shell">op=open, path=env/.env, err=open env/.env: no such file or directory</code></pre>
<p>与此同时，我们得导入 <code>os</code> 包。可见，错误类型并没有解决哨兵错误的调用者和源代码存在强耦合和源代码依赖的问题。</p>
<h3 id="不透明错误"><a href="#不透明错误" class="headerlink" title="不透明错误"></a>不透明错误</h3><p>这是最灵活的错误处理策略，因为它所产生的代码和调用者之间的耦合最少。</p>
<p>这种风格称为 opaque errors ，即不透明错误。因为虽然你知道发生了错误，但你无法看到错误的内部，作为调用者，你只知道操作的结果到底是成功了还是失败了。</p>
<p>这就是不透明错误的全部内容，只需返回错误而无需假设其内容。 如果你采用此策略，那么错误处理作为调试辅助工具将变得更加有用。</p>
<p>考虑以下代码：</p>
<pre><code class="go">import “github.com/quux/bar”

func fn() error &#123;
        x, err := bar.Foo()
        if err != nil &#123;
                return err
        &#125;
        // use x
&#125;</code></pre>
<p>例如，<code>Foo</code> 函数不保证在发生错误的情况下它将返回什么。 <code>Foo</code> 的作者现在可以自由地给它经手的错误添加额外的上下文注释（可能是它自己产生的新错误，也可能是它调用的代码返回的错误），而不会破坏与调用方的约定。</p>
<p>不透明错误的处理需要依赖 <a target="_blank" rel="noopener" href="https://github.com/pkg/errors">pkg/errors</a> 库（ 或者提供了相似 API 的库，Go 1.13 也引进了 <code>errors </code> 包），pkg/errors 最主要的 API 是：</p>
<p><code>Wrap</code> 函数：</p>
<pre><code class="go">type withMessage struct &#123;
    cause error
    msg   string
&#125;

type withStack struct &#123;
    error
    *stack
&#125;

// Wrap 返回一个错误，并给返回的错误附上注释信息，注释信息包括 message 和在调用 Wrap 时的 stack trace。
// 如果 err 为 nil，Wrap 返回 nil。
func Wrap(err error, message string) error &#123;
    if err == nil &#123;
        return nil
    &#125;
    err = &amp;withMessage&#123;
        cause: err,
        msg:   message,
    &#125;
    return &amp;withStack&#123;
        err,
        callers(),
    &#125;
&#125;</code></pre>
<p><code>Cause</code> 函数：</p>
<pre><code class="go">// Cause 返回 err 包含的底层错误。如果 err 有实现 causer 接口，那么会返回 err 的原始错误，如果没有则返回 nil。
func Cause(err error) error &#123;
    type causer interface &#123;
        Cause() error
    &#125;

    for err != nil &#123;
        cause, ok := err.(causer)
        if !ok &#123;
            break
        &#125;
        err = cause.Cause()
    &#125;
    return err
&#125;</code></pre>
<p>可以看到，<a target="_blank" rel="noopener" href="https://github.com/pkg/errors">pkg/errors</a> 库的 <code>Wrap</code> 做的事情就是使用 <code>err + message</code> 包装一个实现了 <code>cause</code> 接口的 err，然后使用 <code>cause err + stack trace</code> 又包装成一个新的 err，简单来说就是 <code>Wrap</code> 在做 error 套娃！因此 <code>Cause</code> 做的事情直白来说就是反套娃了。更详细的 <code>Wrap</code> 和 <code>Cause</code> 介绍请阅读 <a href="##%E9%94%99%E8%AF%AF%E5%A4%84%E7%90%86%E5%BA%93">错误处理库</a> 这一节。</p>
<p>但是，我们必须清楚，不透明错误的存在的意义并不是用来解决哨兵错误或者错误类型的缺点，不透明错误是用来简化错误处理，以及作为调试辅助工具。一个使用不透明错误的例子：</p>
<pre><code class="go">package main

import (
    &quot;fmt&quot;
    &quot;os&quot;

    &quot;github.com/cockroachdb/errors&quot;
)

func main() &#123;
    if err := a(); err != nil &#123;
        fmt.Printf(&quot;a() failed: %+v&quot;, err)
    &#125;
&#125;

func a() error &#123;
    if err := b(); err != nil &#123;
        return err
    &#125;
    return nil
&#125;

func b() error &#123;
    if _, err := os.Open(&quot;config.json&quot;); err != nil &#123;
        return errors.Wrap(err, &quot;打开文件失败&quot;)
    &#125;
    return nil
&#125;
</code></pre>
<p>运行上面这段代码，当文件不存在时会输出：</p>
<pre><code class="shell">a() failed: open config.json: no such file or directory
打开文件失败
main.b
        /Users/boren/projects/goerr/main.go:25 # 在 IDE 的终端窗口点击这一行，会跳转到报错的代码处
main.a
        /Users/boren/projects/goerr/main.go:17
main.main
        /Users/boren/projects/goerr/main.go:11
runtime.main
        /Users/boren/.go/src/runtime/proc.go:250
runtime.goexit
        /Users/boren/.go/src/runtime/asm_arm64.s:1263
Process finished with the exit code 0</code></pre>
<p>使用 <code>Wrap</code> 后，输出的错误信息更加详细了，非常方便调试。</p>
<p>使用 <code>fmt.Printf(&quot;a() failed: %+v&quot;, err)</code> 打印错误信息只适合调试阶段使用，在测试或者生产环境阶段使用则不太合适，因为这个信息以 JSON 格式打印不友好，这时候使用 <code>fmt.Printf(&quot;a() failed: %v&quot;, err)</code> 打印更合适。两者的区别就是 <code>%+v</code> 和 <code>%v</code> 的区别，前者会打印出 err 的 stack trace，后者只会打印 <code>err.Error()</code> 的值。</p>
<h2 id="如何选择错误处理策略"><a href="#如何选择错误处理策略" class="headerlink" title="如何选择错误处理策略"></a>如何选择错误处理策略</h2><p>现在我们了解了上述三种错误处理策略，但是在实际项目开发中我们该用哪一种呢？不透明错误被描述成是最灵活的，我们干脆就用这一种吧！但是很遗憾，不透明错误并非银弹，它无法一并解决 Go 错误处理的各种痛点。现实世界中的 Go 项目，可能无法完全避免哨兵错误和错误类型，而是需要结合三种错误处理策略！</p>
<ul>
<li>对于 API 类型的项目，我们需要返回详细的、分类的错误给调用方，因此这种类型的项目的错误处理很有挑战，很难避免哨兵错误和错误类型。比如：使用 ID 查询资源时，总是要在当 <code>err == sql.ErrNoRows</code> 成立时返回 <code>HTTP 404</code> 给客户端，此处无法避免使用哨兵错误；</li>
<li>对于 API 类型的项目，如果我们确定了返回的具体的 HTTP status code，但还需要返回更详细的信息，那么可以使用错误类型；</li>
<li>对于非接口类的项目，比如后台类、定时任务类项目，我们可能是遇到错误就打印详细的错误信息，并终止执行流程，并不需要区分到详细的错误类型，因此可能会更多地用到不透明错误；</li>
</ul>
<p>我们说的要尽量减少包与包之间存在的耦合关系，尽量减少包与包之间的源代码依赖关系，指的是是要避免非直接调用的包之间的耦合和源代码依赖关系。举个例子，假设存在这样一个调用链条：<code>a.A() -&gt; b.B() -&gt; c.C()</code>，我们要做到 <code>a</code> 包避免导入 <code>c</code>包。<code>a</code> 包天然耦合和依赖 <code>b</code> 包，因此 <code>b</code> 包在必要情况下是可以返回哨兵错误和错误类型给 <code>a</code> 包的。</p>
<p>另外我们需要明白，错误处理策略不是排他的，不是非黑即白的，不是选择了一种就不能用另一种。实际上我们可以在一个 error 上结合了多种策略，比如一下代码示例：</p>
<p>不透明错误结合哨兵错误：</p>
<pre><code class="go">// projtmpl/internal/repository/user/user.go
package user

import (
    &quot;github.com/cockroachdb/errors&quot;
)

type Repository struct &#123;
    DB *sql.DB
&#125;

func (r *Repository) SelectOne(ctx context.Context, id int64) (*model.User, error) &#123;
    user, err := model.FindUser(ctx, r.DB, id)
    return user, errors.Wrap(err, &quot;select one user failed&quot;) // id 对应的 user 不存在时，err 值等于 sql.ErrNoRows，此时 err 被 Wrap 成一个不透明错误
&#125;</code></pre>
<p>不透明错误结合错误类型：</p>
<pre><code class="go">// iCareFiles 项目的一个错误处理案例，调用关系时：contorller/drive 包 -&gt; service/drive 包 -&gt; driver 包

// ===== 分割线 =====
// contorller/drive 包
// NewFolder 实现新建文件夹功能
func (h *Handler) NewFolder(c *gin.Context) &#123;
    // 调用 service 层，开始新建文件
    output, err := h.Services.Drive.NewFolder(&amp;drive.NewFolderInput&#123;
        Drive:            d,
        Name:             req.Name,
        ParentFolderID:   req.ParentFolderID,
        ParentFolderPath: req.ParentFolderPath,
    &#125;)
    if err != nil &#123;
    if authErr, ok := errors.Cause(err).(*drive.ErrUnauthorizedAccess); ok &#123;
      // 识别出了具体的错误类型，返回准确的 HTTP 状态码
            response.UnauthorizedDriveAccess(c, err)
            return
        &#125;
    ...
    &#125;
    ...
&#125;

// ===== 分割线 =====
// service/drive 包
// NewFolder 新建文件夹，可能会返回一个 UnauthorizedDriveAccess 错误
type ErrUnauthorizedAccess struct &#123;
  // DriveType 是云盘类型，1 代表 Google Drive，2 代表 Google Photos
    DriveType  int
  // DriveName 云盘名字
  DriveName int
  // DriveEmail 表示云盘用户的 email
    DriveEmail string
&#125;

// 必须实现 Error() 方法，以表明 *ErrUnauthorizedAccess 实现了 error 接口
func (e *ErrUnauthorizedAccess) Error() string &#123;
  if len(t.DriveEmail) == 0 &#123;
        return fmt.Sprintf(
            &quot;Your %s authorization to iCareFiles has expired&quot;,
            DriveName,
        )
    &#125;
    return fmt.Sprintf(
        &quot;Your %s(%s) authorization to iCareFiles has expired&quot;,
        DriveName,
        t.DriveEmail,
    )
&#125;

// NewFolder 是 service 层的新建文件，负责调用网盘访问层的新建文件夹接口
func (s *Service) NewFolder(input *NewFolderInput) (*NewFolderOutput, error) &#123;
    ...
    out, err := drive.NewFolder(&amp;params)
    if err != nil &#123;
    if authErr, ok := errors.Cause(err).(*driver.UnauthorizedDriveAccess); ok &#123;
      // 做类型断言，如果是 *driver.UnauthorizedDriveAccess，那么返回 ErrUnauthorizedAccess
      return &amp;ErrUnauthorizedAccess&#123;
        DriveType: authErr.DriveType, 
        DriveName: modext.DriveNameFromType(t.DriveType), 
        DriveEmail: authErr.DriveEmail,
      &#125;
    &#125;
        return nil, errors.Wrapf(err, &quot;new folder failed&quot;) // NewFolder 返回错误类型 UnauthorizedDriveAccess 时，在这里被 Wrap 成一个不透明错误
    &#125;
    ...
&#125;

// ===== 分割线 =====
// driver 包
// 位于文件：pkg/driver/dropbox.go
// UnauthorizedDriveAccess 是一个错误类型，当遇到这种错误时，前端页面需要展示用户 email 是 xxx 的 yyy 网盘的授权访问过期了，
// 引导用户再次完成授权流程
type UnauthorizedDriveAccess struct &#123;
  // DriveType 是云盘类型，1 代表 Google Drive，2 代表 Google Photos
    DriveType  int
  // DriveEmail 表示云盘用户的 email
    DriveEmail string
&#125;

// 必须实现 Error() 方法，以表明 *UnauthorizedDriveAccess 实现了 error 接口
func (t *UnauthorizedDriveAccess) Error() string &#123;
  return fmt.Sprintf(&quot;drive type: t.DriveType, drive email: t.DriveEmail&quot;)
&#125;

// NewFolder 是网盘访问层的新建文件夹，负责具体调用 Dropbox 的接口新建文件夹
func (d *Dropbox) NewFolder(input *NewFolderParameters) (*NewFolderResult, error) &#123;
    ...
    if !resp.IsSuccess() &#123;
        if resp.StatusCode() == http.StatusUnauthorized &#123;
            return nil, &amp;UnauthorizedDriveAccess&#123;
        DriveType: modext.Dropbox, 
        DriveEmail: input.Drive.AccountEmail.String,
      &#125;
        &#125;
        return nil, errors.Newf(&quot;new Dropbox folder failed: code=%d, msg=%s&quot;, resp.StatusCode(), resp.String())
    &#125;
  ...
&#125;
</code></pre>
<h2 id="错误处理库"><a href="#错误处理库" class="headerlink" title="错误处理库"></a>错误处理库</h2><p>由前一节内容可以看到，不透明错误的处理依赖错误处理工具库。Go 生态里最先开始流行的库是 <a target="_blank" rel="noopener" href="https://github.com/pkg/errors">pkg/errors</a> ，后来 Go 官方在 Go 1.13 标准库里添加了 errors 包 以及 <code>fmt.Errorf()</code> ，这个组合基本上可以完成跟 <a target="_blank" rel="noopener" href="https://github.com/pkg/errors">pkg/errors</a> 同样的功能，除了 <code>fmt.Errorf()</code> 不能像  <a target="_blank" rel="noopener" href="https://github.com/pkg/errors">pkg/errors</a>  的 Wrap 一样保留 stack trace 外。</p>
<p>可能是由于 errors 包 以及 <code>fmt.Errorf()</code> 组合无法满足需求，Go 生态里仍然有很多开发者在开发和维护错误处理库，常见的选择有：</p>
<ul>
<li><a target="_blank" rel="noopener" href="https://github.com/pkg/errors">pkg/errors</a></li>
<li><a target="_blank" rel="noopener" href="https://github.com/golang/xerrors">xerrors</a></li>
<li><a target="_blank" rel="noopener" href="https://github.com/joomcode/errorx">joomcode/errorx</a></li>
<li><a target="_blank" rel="noopener" href="https://github.com/cockroachdb/errors">cockroachdb/errors</a></li>
<li>…</li>
</ul>
<p><a target="_blank" rel="noopener" href="https://github.com/cockroachdb/errors">cockroachdb/errors</a> 的功能和 star 数最多，因此更推荐使用这个。cockroachdb/errors 常用的函数有：</p>
<ul>
<li><p><code>New(msg string) error</code> 构造一个新的 err 并保留 stack trace；</p>
</li>
<li><p><code>Newf(format string, args ...interface&#123;&#125;) error</code> 同上，但是使用格式化后的字符串；</p>
</li>
<li><p><code>Wrap(err error, msg string) error</code> 使用 err 和 msg 包装出一个新的 error 并保留 stack trace；</p>
</li>
<li><p><code>Cause(err error) error</code> 获取根因错误，即获取 <code>Wrap(err error, msg string) error</code> 传进来的参数 err；</p>
</li>
<li><p><code>WithMessage(err error, message string) error</code> 使用 err 和 msg 包装出一个新的 error 但<strong>不会保留</strong> stack trace；</p>
</li>
<li><p><code>WithMessagef(err error, format string, args ...interface&#123;&#125;) error</code> 同上；</p>
</li>
<li><p><code>WithStack(err error) error</code> 使用 err 和 stack trace 包装出一个新的 error </p>
</li>
<li><p><code>Is(err, reference error) bool</code> 检查 err 包装着的所有的 error，如有任一个 error 的类型跟 <code>reference</code> 一样，则返回 true；</p>
</li>
<li><p><code>IsAny(err error, references ...error) bool</code> 同上，区别是 <code>...error</code> 表示可以传多个 <code>reference</code>；</p>
</li>
<li><p><code>HasInterface(err error, referenceInterface interface&#123;&#125;) bool</code> 检查 err 是否包含有实现了 <code>referenceInterface</code> 接口的 error，有的话返回 true。<code>referenceInterface</code> 必须是指向接口的指针；</p>
</li>
<li><p><code>WithSecondaryError(err error, additionalErr error) error</code> 使用次要的错误 <code>additionalErr</code> 增强主错误 <code>err</code> ，并且 <code>additionalErr</code> 在 <code>Cause</code> 等函数中不起作用；</p>
</li>
</ul>
<h2 id="错误处理实践"><a href="#错误处理实践" class="headerlink" title="错误处理实践"></a>错误处理实践</h2><p>在了解了错误处理库后，在开发中我们可以以 <a target="_blank" rel="noopener" href="https://dave.cheney.net/">Dave Cheney</a> 的总结为指南：</p>
<ol>
<li><p>使用 <code>errors.New</code> 或者 <code>errors.Newf</code> 生成一个新的错误并返回：</p>
<pre><code class="go">func parseArgs(args []string) error &#123;
    if len(args) &lt; 3 &#123;
        return errors.Newf(&quot;args length is %d, expect %d&quot;, len(args), 3)
    &#125;
&#125;</code></pre>
</li>
<li><p>与标准库或者第三方的库（GitHub 上的 ）进行协作的时候，考虑使用 <code>errors.Wrap</code> 或者 <code>errors.Wrapf</code> 包装错误以保存 stack trace：</p>
<pre><code class="go">f, err := os.Open(path)
if err != nil &#123;
    return errors.Wrapf(err, &quot;failed to open %q&quot;, path)
&#125;</code></pre>
</li>
<li><p>如果你从另一个函数收到错误，通常只需返回它就足够了。因为按照上面第 1 点，你得到的错误已经是一个已经加了上下文信息和 stack trace 的错误，所以无需再重复添加上下文信息：</p>
<pre><code class="go">err := parseArgs()
if err != nil &#123;
    return err
&#125;</code></pre>
</li>
<li><p>始终将错误返回给调用者，而不是在每处都打印日志；</p>
</li>
<li><p>在程序的顶层或工作 goroutine 的顶层，使用 <code>%+v</code> 以足够详细的方式打印错误：</p>
<pre><code class="go">func main() &#123;
    err := app.Run()
    if err != nil &#123;
        log.Print(err)
        os.Exit(1)
    &#125;
&#125;</code></pre>
</li>
<li><p>如果你想从打印中排除某些类别的错误，请在打印错误之前使用 <code>errors.Cause</code> 解开错误。</p>
</li>
</ol>
<h2 id="错误处理技巧"><a href="#错误处理技巧" class="headerlink" title="错误处理技巧"></a>错误处理技巧</h2><h3 id="Fail-fast-尽早处理错误"><a href="#Fail-fast-尽早处理错误" class="headerlink" title="Fail-fast: 尽早处理错误"></a>Fail-fast: 尽早处理错误</h3><p>Go 代码里 <code>if err != nil &#123;&#125;</code> 会非常多，所以我们要在每次遇到错误时就立马处理错误，避免有过多的嵌套代码块。示例：</p>
<p>这样做：</p>
<pre><code class="go">f, err := func1()
if err != nil &#123;
    // 处理错误
&#125;

// 没有错误，继续执行流程
err = func2()
if err != nil &#123;
    // 处理错误
&#125;

// 没有错误，继续执行流程
err = func3()
if err != nil &#123;
    // 处理错误
&#125;

return nil</code></pre>
<p>不要这样做：</p>
<pre><code class="go">f, err := os.func1()
if err == nil &#123;
    // 没有错误，继续执行流程
    err = func2()
    if err == nil &#123;
        // 没有错误，继续执行流程
        err = func3()
        if err == nil &#123;
            // 没有错误，继续执行流程
            return nil
        &#125;
        // 有错误，处理错误
    &#125;
        // 有错误，处理错误
&#125;</code></pre>
<p>这两种写法中第 1 种更合理，且可读性更好；第 2 种写法是糟糕的，代码有很多缩进块，可读性很差。人脑天生不适合去理解这种层层嵌套的东西（想想递归函数，你能往脑袋里压进所有的递归调用吗😂）。</p>
<h3 id="通过减少错误出现的次数的方式去减少错误处理的次数"><a href="#通过减少错误出现的次数的方式去减少错误处理的次数" class="headerlink" title="通过减少错误出现的次数的方式去减少错误处理的次数"></a>通过减少错误出现的次数的方式去减少错误处理的次数</h3><p>要这样子：</p>
<pre><code class="go">func AuthenticateRequest(r *Request) error &#123;
    return authenticate(r.User)
&#125;</code></pre>
<p>不要这样子：</p>
<pre><code class="go">func AuthenticateRequest(r *Request) error &#123;
    err := authenticate(r.User)
    if err != nil &#123;
        return err
    &#125;
    return nil
&#125;</code></pre>
<p>来看一个 Rob Pike 的更加巧妙的例子：</p>
<pre><code class="go">_, err = fd.Write(p0[a:b])
if err != nil &#123;
    return err
&#125;
_, err = fd.Write(p1[c:d])
if err != nil &#123;
    return err
&#125;
_, err = fd.Write(p2[e:f])
if err != nil &#123;
    return err
&#125;
// and so on</code></pre>
<p>这段代码有 3 个错误是否为 nil 的检查，这些重复、繁琐的代码让代码失去了优雅。应用同样的原理，这段代码可以优化为：</p>
<pre><code class="go">type errWriter struct &#123;
    w   io.Writer
    err error
&#125;

func (ew *errWriter) write(buf []byte) &#123;
    if ew.err != nil &#123;
        return
    &#125;
    _, ew.err = ew.w.Write(buf)
&#125;

ew := &amp;errWriter&#123;w: fd&#125;
ew.write(p0[a:b])
ew.write(p1[c:d])
ew.write(p2[e:f])
// and so on
if ew.err != nil &#123;
    return ew.err
&#125;</code></pre>
<p>最后得到的代码更加简洁、优雅。</p>
<h3 id="每个错误只处理一次"><a href="#每个错误只处理一次" class="headerlink" title="每个错误只处理一次"></a>每个错误只处理一次</h3><p><a target="_blank" rel="noopener" href="https://dave.cheney.net/">Dave Cheney</a> （Go 项目常年活跃的贡献者）在 <a target="_blank" rel="noopener" href="https://dave.cheney.net/2016/04/27/dont-just-check-errors-handle-them-gracefully">Don’t just check errors, handle them gracefully</a> 中提到，错误只应该处理一次，处理错误意味着检查错误值并做出决定。这句话的意思每一次检查错误，我们只应该做出一个选择。</p>
<p>对于一个错误，如果你做出少于一次的选择（没有接收函数返回的 error，或者接收了但不处理），你就是在忽略错误。就像我们在这里看到的，<code>w.Write</code> 返回的错误没有被接收：</p>
<pre><code class="go">func Write(w io.Writer, buf []byte) &#123;
        w.Write(buf)
&#125;</code></pre>
<p>对于一个错误，如果你做出多于一次的选择也是有问题的：</p>
<pre><code class="go">func Write(w io.Writer, buf []byte) error &#123;
        _, err := w.Write(buf)
        if err != nil &#123;
                // annotated error goes to log file
                log.Println(&quot;unable to write:&quot;, err)

                // unannotated error returned to caller
                return err
        &#125;
        return nil
&#125;</code></pre>
<p>在这个例子中，如果 <code>w.Write</code> 返回了一个错误，那么代码会打印一条日志，接下来这个错误被返回给 <code>Write</code> 的调用者，而 <code>Write</code> 的调用者也有可能会做同样的操作：打印日志，然后继续向上透传。</p>
<p>这样我们得到了多余的、重复的日志打印，这是很糟糕的，无益于我们跟踪错误。而且在调用链的开始处，我们得到的是没有任何上下文的原始错误，导致我们无法判断错误是从调用链中的哪一个节点抛出的。<code>Wrap errors</code> 这个时候派上了用场：</p>
<pre><code class="go">func Write(w io.Write, buf []byte) error &#123;
        _, err := w.Write(buf)
        return errors.Wrap(err, &quot;write failed&quot;)
&#125;</code></pre>
<p>使用 errors package，给错误添加上下文信息和 stack trace，这样程序员和机器都能很好地检查错误。</p>
<h3 id="断言错误的行为，而不是类型"><a href="#断言错误的行为，而不是类型" class="headerlink" title="断言错误的行为，而不是类型"></a>断言错误的行为，而不是类型</h3><p>在少数情况下，opaque error 这种非此即彼的错误处理方法是不够的。有一些场景我们是需要详细的 error 信息的、底层的错误，</p>
<p>例如，与进程外的世界进行交互，需要调用方调查错误的性质，以确定是否需要重试。在这种情况下，我们检查错误实现了特定的行为，而不是断言错误是特定的类型或值。考虑这个例子:</p>
<pre><code class="go">type temporary interface &#123;
    Temporary() bool
&#125;

func IsTemporary(err error) bool &#123;
    te, ok := err.(temporary)
    return ok &amp;&amp; te.Temporary()
&#125;

func main() &#123;
    err := ...
    if IsTemporary(err) &#123; 
        ...
    &#125;
&#125;</code></pre>
<p>我们可以将任何错误传递给 <code>IsTemporary(err error) bool</code> 以确定是否可以重试该错误。</p>
<p>如果 err 没有实现 <code>temporary</code> 接口，也就是它没有 <code>Temporary()</code> 方法，那么 error 不是临时的。</p>
<p>如果错误确实实现了 <code>temporary</code> 接口，那么如果  <code>Temporary()</code> 返回 true，调用者也许可以重试操作。</p>
<p>这里的关键是，我们可以在不导入定义错误的程序包，或者说可以在不了解有关错误底层类型的任何信息的情况下实现此逻辑。我们只需要知道 err 是否实现了有 <code>Temporary()</code> 方法的接口即可。</p>
<h3 id="errors-Wrap-偷懒小技巧"><a href="#errors-Wrap-偷懒小技巧" class="headerlink" title="errors.Wrap 偷懒小技巧"></a>errors.Wrap 偷懒小技巧</h3><p>代码片段：</p>
<pre><code class="go">func (r *Repository) SelectOne(ctx context.Context, id int64) (*model.User, error) &#123;
  if user, err := model.FindUser(ctx, r.DB, id); err != nil &#123;
    return nil, errors.Wrap(err, &quot;select one user failed&quot;)
  &#125; else &#123;
    return user, nil
  &#125;
&#125;</code></pre>
<p>可以优化为：</p>
<pre><code class="go">func (r *Repository) SelectOne(ctx context.Context, id int64) (*model.User, error) &#123;
    user, err := model.FindUser(ctx, r.DB, id)
    return user, errors.Wrap(err, &quot;select one user failed&quot;)
&#125;</code></pre>
<p>这是一个能让代码更简洁的小技巧，但使用场景有限，仅适用于 <code>user, err := model.FindUser(ctx, r.DB, id)</code> 这行代码后面跟着整个函数的最后一个 <code>return</code> 语句这个场景。</p>
<p>为什么这个场景可以这样写呢？查看 <code>errors.Wrap(err error, message string)</code> 的源码就明白了：</p>
<pre><code class="go">// Wrap returns an error annotating err with a stack trace
// at the point Wrap is called, and the supplied message.
// If err is nil, Wrap returns nil.
func Wrap(err error, message string) error &#123;
    if err == nil &#123;
        return nil
    &#125;
    err = &amp;withMessage&#123;
        cause: err,
        msg:   message,
    &#125;
    return &amp;withStack&#123;
        err,
        callers(),
    &#125;
&#125;</code></pre>
<p>当 <code>err == nil</code> 成立时，<code>Wrap</code> 会直接返回 nil，此时 <code>message</code> 参数是用不到的；而当 <code>err == nil</code> 不成立时，<code>Wrap</code> 将使用 <code>err</code> 和 <code>message</code> 包装构造一个新的 error。</p>
<h2 id="参考"><a href="#参考" class="headerlink" title="参考"></a>参考</h2><ul>
<li><a target="_blank" rel="noopener" href="https://blog.golang.org/errors-are-values">Errors are values</a></li>
<li><a target="_blank" rel="noopener" href="https://dave.cheney.net/2016/04/27/dont-just-check-errors-handle-them-gracefully">Don’t just check errors, handle them gracefully</a></li>
<li><a target="_blank" rel="noopener" href="https://dave.cheney.net/2016/06/12/stack-traces-and-the-errors-package">Stack traces and the errors package</a></li>
<li><a target="_blank" rel="noopener" href="https://blog.golang.org/error-handling-and-go">Error handling and Go</a></li>
</ul>
</div></div></body><script src="/js/highlight.min.js"></script><script src="/js/main.js"></script><script src="/js/bootstrap/bootstrap.min.js"></script><script>window.dataLayer = window.dataLayer || [];
function gtag(){dataLayer.push(arguments);}
gtag('js', new Date());
gtag('config', '');</script></html>